sensors:
  - overhead_camera
  - front_camera

overhead_camera:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /overhead_camera/points
  max_range: 5.0
  point_subsample: 1
  padding_offset: 0.03375     # was 0.03
  padding_scale: 1.0
  max_update_rate: 10.0
  filtered_cloud_topic: /overhead_camera/filtered_points

front_camera:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /front_camera/points
  max_range: 5.0
  point_subsample: 1
  padding_offset: 0.03375     # was 0.03
  padding_scale: 1.0
  max_update_rate: 10.0
  filtered_cloud_topic: /front_camera/filtered_points